---

php_apt_key_server: keyserver.ubuntu.com
php_apt_key_id: AC0E47584A7A714D
php_version: "5.6"
php_repository: https://packages.sury.org/php
php_fpm_config_file: /etc/php/{{ php_version }}/fpm/pool.d/www.conf

# Lizmap nginx frontal
lizmap_port: 80
lizmap_hostname: lizmap.local


lizmap_fpm_socket: /var/run/php/php{{ php_version }}-fpm.sock

lizmap_webserver_user: vagrant
lizmap_webserver_group: vagrant

lizmap_jauth_driver: sqlite3
# or pgsql. If so, auth and acl configuration will be store in PostgreSQL database
# only if postgresql has already been installed


# the path should be equals to the vagrant mount point, see config.vm.synced_folder in Vagrantfile
lizmap_home: /lizmap_web_client
lizmap_data_directory: /lizmap_web_client/data/
