[
    {
        "name": "buffer_500",
        "title": "Buffer 500m around this object",
        "scope": "feature",
        "layers": [
            "parent_layer_d3dc849b_9622_4ad0_8401_ef7d75950111",
            "tramway_lines_4215fd0b_5136_4c19_b3ee_d1617f8df8ea"
        ],
        "confirm": "Do you really want to show the buffer ?",
        "icon": "icon-leaf",
        "options": {
            "buffer_size": 500,
            "other_param": "yes"
        },
        "style": {
            "graphicName": "circle",
            "pointRadius": 6,
            "fill": true,
            "fillColor": "lightblue",
            "fillOpacity": 0.3,
            "stroke": true,
            "strokeWidth": 4,
            "strokeColor": "blue",
            "strokeOpacity": 0.8
        },
        "callbacks": [
            {
                "method": "zoom"
            },
            {
                "method": "select",
                "layerId": "parent_layer_d3dc849b_9622_4ad0_8401_ef7d75950111"
            },
            {
                "method": "redraw",
                "layerId": "parent_layer_d3dc849b_9622_4ad0_8401_ef7d75950111"
            }
        ]
    },
    {
        "name": "project_map_center_buffer",
        "title": "Get the buffer of the curent map center point",
        "description": "This is an example action which returns a circle at the center of the map",
        "scope": "project",
        "icon": "icon-star",
        "options": {
            "buffer_size": 2000
        },
        "style": {
            "graphicName": "circle",
            "pointRadius": 6,
            "fill": true,
            "fillColor": "orange",
            "fillOpacity": 0.3,
            "stroke": true,
            "strokeWidth": 4,
            "strokeColor": "red",
            "strokeOpacity": 0.8
        },
        "callbacks": []
    },
    {
        "name": "layer_spatial_extent",
        "title": "Get the contour of all the layer features",
        "description": "This action will draw a polygon which represent the contour of all the features",
        "scope": "layer",
        "layers": [
            "parent_layer_d3dc849b_9622_4ad0_8401_ef7d75950111"
        ],
        "icon": "icon-star",
        "options": {},
        "style": {
            "graphicName": "circle",
            "pointRadius": 6,
            "fill": true,
            "fillColor": "orange",
            "fillOpacity": 0.3,
            "stroke": true,
            "strokeWidth": 4,
            "strokeColor": "red",
            "strokeOpacity": 0.8
        },
        "callbacks": [
            {
                "method": "zoom"
            }
        ]
    }
]
