[
    {
        "name": "buffer_500",
        "title": "Buffer 500m around this object",
        "scope": "feature",
        "layers": [
            "parent_layer_d3dc849b_9622_4ad0_8401_ef7d75950111",
            "tramway_lines_4215fd0b_5136_4c19_b3ee_d1617f8df8ea"
        ],
        "confirm": "Do you really want to show the buffer ?",
        "icon": "icon-leaf",
        "options": {
            "buffer_size": 500,
            "other_param": "yes"
        },
        "style": {
            "circle-radius": 6,
            "circle-stroke-color": "blue",
            "circle-stroke-width": 4,
            "circle-fill-color": "rgba(173,216,230,0.8)",
            "stroke-color": "blue",
            "stroke-width": 4,
            "fill-color": "rgba(173,216,230,0.8)"
        },
        "callbacks": [
            {
                "method": "zoom"
            },
            {
                "method": "select",
                "layerId": "parent_layer_d3dc849b_9622_4ad0_8401_ef7d75950111"
            },
            {
                "method": "redraw",
                "layerId": "parent_layer_d3dc849b_9622_4ad0_8401_ef7d75950111"
            }
        ]
    },
    {
        "name": "project_map_center_buffer",
        "title": "Get the buffer of the current map center point",
        "description": "This is an example action which returns a circle at the center of the map",
        "scope": "project",
        "icon": "icon-star",
        "options": {
            "buffer_size": 2000
        },
        "style": {
            "fill-color": "rgba(255,165,0,0.3)",
            "stroke-width": 4,
            "stroke-color": "rgba(255,0,0,0.8)"
        },
        "callbacks": []
    },
    {
        "name": "project_map_drawn_point_buffer",
        "title": "Get the buffer of the point drawn by the user",
        "description": "This is an example action which returns a buffer around a point drawn by the user",
        "scope": "project",
        "icon": "icon-star",
        "geometry": "point",
        "options": {
            "buffer_size": 2000
        },
        "style": {
            "fill-color": "rgba(255,165,0,0.3)",
            "stroke-width": 4,
            "stroke-color": "rgba(255,0,0,0.8)"
        },
        "callbacks": []
    },
    {
        "name": "layer_spatial_extent",
        "title": "Get the contour of all the layer features",
        "description": "This action will draw a polygon which represents the contour of all the features",
        "scope": "layer",
        "layers": [
            "parent_layer_d3dc849b_9622_4ad0_8401_ef7d75950111"
        ],
        "icon": "icon-star",
        "options": {},
        "style": {
            "fill-color": "rgba(255,165,0,0.3)",
            "stroke-width": 4,
            "stroke-color": "rgba(255,0,0,0.8)"
        },
        "callbacks": [
            {
                "method": "zoom"
            }
        ]
    }
]
