SHELL:=bash
.ONESHELL:
.PHONY: env

clean:
	find . -name "*.qgs~" -type f -delete
	find . -name "*-shm" -type f -delete
	find . -name "*-wal" -type f -delete
	find . -name "*_attachments.zip" -type f -delete
