
- name: install spatialite
  apt: name=libsqlite3-mod-spatialite state=present
  tags: php

- name: Setup sqlite extension directory
  file: path=/srv/sqlite_ext/ state=directory
  tags: php

- name: Copy mod_spatialite into /srv/sqlite_ext
  copy:
    src: "{{ libspatialite_path }}"
    dest: /srv/sqlite_ext/mod_spatialite.so
    remote_src: yes
  tags: php
  notify:
    - restart php-fpm

- name: setup sqlite extension directory into php.ini
  ini_file:
    dest: "{{ php_fpm_conf_path }}php.ini"
    section: "sqlite3"
    option: "sqlite3.extension_dir"
    value: "/srv/sqlite_ext/"
  tags: php
  notify:
    - restart php-fpm

