version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 6 5 */3 *"
    assignees:
      - "Gustry"

  - package-ecosystem: "composer"
    directory: "/lizmap"
    schedule:
      interval: "cron"
      cronjob: "0 6 5 */3 *"

  - package-ecosystem: "composer"
    directory: "/tests/units"
    schedule:
      interval: "cron"
      cronjob: "0 6 5 */3 *"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 6 5 */3 *"
#    assignees:
#      - "nboisteault"
