version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "Gustry"

  - package-ecosystem: "composer"
    directory: "/lizmap"
    schedule:
      interval: "monthly"
    assignees:
      - "laurentj"

  - package-ecosystem: "docker"
    directory: "/tests"
    schedule:
      interval: "monthly"
    assignees:
      - "dmarteau"

  - package-ecosystem: "npm"
    directory: "/assets"
    schedule:
      interval: "monthly"
    assignees:
      - "nboisteault"
