"administration pages":
  - any: [
      'lizmap/modules/admin/**',
    ]

"CI & packages":
  - any: [
      '.github/**',
      '.gitlab-ci.yml',
      'Makefile',
    ]

"data editor":
  - any: [
      'lizmap/modules/lizmap/lib/Form/**',
    ]

"dataviz":
  - any: [
    'lizmap/modules/dataviz/**',
    'lizmap/www/assets/js/dataviz/**',
  ]

"docker":
  - any: [
      'docker/**',
    ]

"javascript":
  - any: [
    'assets/**',
    'lizmap/www/assets/js/**',
    'assets/src/modules/**',
    'tests/js-units/**',
  ]

#"run cypress":
#  - any: ['tests/end2end/**/*']

"QGIS Server":
  - any: [
      'lizmap/modules/lizmap/lib/Request/**',
    ]

"tests":
  - any: [
      'tests/**',
    ]
