# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: ^lizmap/app/overloads|lizmap/app/themes|lizmap/www/assets/
      - id: end-of-file-fixer
        exclude: ^lizmap/app/overloads|lizmap/app/themes|lizmap/www/assets/
      - id: check-yaml
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: check-added-large-files

#  - repo: local
#    hooks:
#      - id: php-cs-fixer
#        name: PHP CS Fixer
#        # To match value in Makefile
#        entry: oskarstark/php-cs-fixer-ga:3.26.0 --allow-risky=yes --config=.php-cs-fixer.dist.php
#        language: docker_image
