#!/usr/bin/env bash

set -e

CMD=$1;
if [ -z "$CMD" ]; then
    CMD="up -d"
else
    shift
fi

# Re-create environment
make env

if [ "$CMD" == "reset" ]; then
    # Purge docker conainers/volumes
    make reset
    exit 0
elif [ "$CMD" == "build" ]; then
    make build-plugins
fi

docker-compose $CMD "$@"  

