#!/usr/bin/env bash

set -e

export LIZMAP_USER_ID=${LIZMAP_USER_ID:-$(id -u)}
export LIZMAP_GROUP_ID=${LIZMAP_GROUP_ID:-$(id -g)}

CMD=$1

if [ "$CMD" == "" ]; then
    CMD="up -d"
fi

if [ "$LZMBRANCH" == "" ]; then
  export LZMBRANCH=$(git rev-parse --abbrev-ref HEAD)
fi


if [ "$LZMPGPORT" == "" ]; then
  export LZMPGPORT=8132
fi

if [ "$LZMQGSRVPORT" == "" ]; then
  export LZMQGSRVPORT=8131
fi

if [ "$LZMWEBPORT" == "" ]; then
  export LZMWEBPORT=8130
fi


docker-compose -p lizmap-${LZMBRANCH}-tests $CMD
