#!/usr/bin/env bash

set -e

export LIZMAP_USER_ID=${LIZMAP_USER_ID:-$(id -u)}
export LIZMAP_GROUP_ID=${LIZMAP_GROUP_ID:-$(id -g)}

CMD=$1

if [ "$CMD" == "" ]; then
  CMD="up -d"
fi

# Install or update Lizmap as a QGIS Server plugin
if [ "$CMD" != "stop" ]; then
  curl "https://packages.3liz.org/pub/lizmap-qgis-plugin/dev/lizmap-qgis-plugin.dev.zip" --output lizmap-qgis-plugin.dev.zip --silent
  unzip -qq lizmap-qgis-plugin.dev.zip
  rm lizmap-qgis-plugin.dev.zip
  rm -rf qgis-server-plugins/lizmap/
  mv lizmap qgis-server-plugins/
fi

if [ "$LZMBRANCH" == "" ]; then
  export LZMBRANCH=$(git rev-parse --abbrev-ref HEAD)
fi


if [ "$LZMPGPORT" == "" ]; then
  export LZMPGPORT=8132
fi

if [ "$LZMQGSRVPORT" == "" ]; then
  export LZMQGSRVPORT=8131
fi

if [ "$LZMWEBPORT" == "" ]; then
  export LZMWEBPORT=8130
fi


docker-compose -p lizmap-${LZMBRANCH}-tests $CMD
