---
# Install Lizmap from github

- name: Install python-qgis for Debian
  package: name={{ item }} state=present
  with_items:
    - python-qgis
  when: qgis_install_source == 'repository' and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
  tags: qgis,plugins

- name: Check git is installed
  package: name={{ item }} state=present
  with_items:
    - git
  tags: qgis,plugins

- name: Add QGIS plugins directory
  file: path={{ qgis_server_plugin_directory }} state=directory owner="{{ qgis_server_plugin_owner }}" group="{{ qgis_server_plugin_group }}" mode="{{ qgis_server_plugin_mode }}"
  tags: qgis,plugins

- set_fact:
    qgis_server_plugins: "{{ qgis2_server_plugins }}"
  when: qgis_server_version == "2.18"

- set_fact:
    qgis_server_plugins: "{{ qgis3_server_plugins }}"
  when: qgis_server_version != "2.18"


- name: Install QGIS server plugins from github
  git: repo={{ item.value.repository }}
    version={{ item.value.version }}
    dest="{{ qgis_server_plugin_directory }}/{{ item.key }}"
    depth=1
    accept_hostkey=yes
  with_dict: "{{ qgis_server_plugins }}"
  register: qgis_plugins_installed
  tags: qgis,plugins

- name: Restart Supervisor Debian
  shell: echo "Restart Supervisor"
  notify:
    - restart supervisor
  when: qgis_plugins_installed.changed
  tags: qgis,plugins

