name: â“ Support/Questions
description: Questions about using or installing Lizmap. 3Liz's paid support => https://www.3liz.com/services.html#3liz-support-offer
title: "[Question]: "
labels: [question]
body:

  - type: markdown
    attributes:
      value: |
        Before asking your question, please check that the response is not in the documentation: https://docs.3liz.com/
        
        Questions about using or installing Lizmap. 3Liz's paid support => https://www.3liz.com/services.html#3liz-support-offer

  - type: textarea
    id: what
    attributes:
      label: What is the question? (in English)
      placeholder: When clicking on button...
    validations:
      required: true

  - type: textarea
    id: versions
    attributes:
      label: Versions, safeguards, check summary etc
      description: |
        You must go in QGIS Desktop, then Lizmap plugin, right click on your server, then "Copy versions in the clipboard". Finally paste here. There isn't any personal data provided.
        Check any messages displayed by the plugin if any. Read https://docs.lizmap.com/current/en/publish/lizmap_plugin/information.html#request-for-support
        Do not make a screenshot, it's not a searchable by a search engine for instance.
    validations:
      required: true

  - type: checkboxes
    id: lizmap-plugin
    attributes:
      label: Check Lizmap plugin
      options:
        - label: I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.
#          required: true

  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: Ubuntu 20.04, Windows 10, ...
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: Browsers
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
    validations:
      required: true

  - type: input
    id: browsers-version
    attributes:
      label: Browsers version
      placeholder: Firefox 89, Chrome 90, ...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        WARNING: obfuscate all sensible data (IP, passwords, domain name...).
        Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
        To find logs in your browser, open developer console (F12 or Ctrl + Shift + I).
        Lizmap error logs can be found in admin panel.
      render: shell
