blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/3liz/lizmap-documentation/issues
    about: Please fill an issue about documentation here.
  - name: Lizmap QGIS plugin issue
    url: https://github.com/3liz/lizmap-plugin/issues
    about: Please fill an issue about Lizmap QGIS plugin here.
