blank_issues_enabled: false
contact_links:
  - name: Additional JavaScript issue
    url: https://docs.lizmap.com/current/en/publish/customization/javascript.html
    about: >
      If the issue concerns a third party JavaScript script then it is not related in Lizmap Web Client source
      code. Please raise your issue in the dedicated bug tracker for this script.
  - name: Question or support
    url: https://discourse.osgeo.org/c/qgis/lizmap/48
    about: >
      GitHub issues are for bug reports and suggestions for new features.
      Questions should go to on another channel, such as the OSGEO Discourse or GIS StackExchange with the "lizmap" tag.
  - name: Documentation
    url: https://github.com/3liz/lizmap-documentation/issues
    about: Please fill an issue about documentation here.
  - name: Lizmap QGIS plugin issue
    url: https://github.com/3liz/lizmap-plugin/issues
    about: Please fill an issue about Lizmap QGIS plugin here.
