
ALTER TABLE jlx_user ADD COLUMN firstname VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE jlx_user ADD COLUMN lastname VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE jlx_user ADD COLUMN organization VARCHAR(100) DEFAULT '';
ALTER TABLE jlx_user ADD COLUMN phonenumber VARCHAR(20) DEFAULT '';
ALTER TABLE jlx_user ADD COLUMN street VARCHAR(150) DEFAULT '';
ALTER TABLE jlx_user ADD COLUMN postcode VARCHAR(10) DEFAULT '';
ALTER TABLE jlx_user ADD COLUMN city VARCHAR(150) DEFAULT '';
ALTER TABLE jlx_user ADD COLUMN country VARCHAR(100) DEFAULT '';
ALTER TABLE jlx_user ADD COLUMN comment TEXT DEFAULT '';
