
- name: configure slapd package *1
  debconf:
    name: slapd
    question: slapd/internal/adminp
    value: "{{ ldap_admin_pwd }}"
    vtype: password

- name: configure slapd package *2
  debconf:
    name: slapd
    question: slapd/password1
    value: "{{ ldap_admin_pwd }}"
    vtype: password

- name: configure slapd package *3
  debconf:
    name: slapd
    question: slapd/password2
    value: "{{ ldap_admin_pwd }}"
    vtype: password

- name: configure slapd package *4
  debconf:
    name: slapd
    question: slapd/internal/generated_adminpw
    value: "{{ ldap_admin_pwd }}"
    vtype: password


- name: configure slapd package *5
  debconf:
    name: slapd
    question: shared/organization
    value: "{{ ldap_org }}"
    vtype: string


- name: configure slapd package *6
  debconf:
    name: slapd
    question: slapd/domain
    value: "{{ lizmap_hostname }}"
    vtype: string

- name: Install Slapd
  apt: name=slapd state=present

- name: Install ldap-utils
  apt: name=ldap-utils state=present
