CREATE TABLE IF NOT EXISTS %%PREFIX%%JLX_USER (
  USR_LOGIN VARCHAR2(50 CHAR) NOT NULL,
  USR_PASSWORD VARCHAR2(50 CHAR) NOT NULL,
  USR_EMAIL VARCHAR2(255 CHAR) DEFAULT NULL,
  CONSTRAINT JLX_USER_PKEY PRIMARY KEY (USR_LOGIN)
);
