--DROP TABLE IF EXISTS jacl_group;
--DROP TABLE IF EXISTS jacl_right_values;
--DROP TABLE IF EXISTS jacl_right_values_group;
--DROP TABLE IF EXISTS jacl_rights;
--DROP TABLE IF EXISTS jacl_subject;
--DROP TABLE IF EXISTS jacl_user_group;
