name: "⏰ End2end scheduler"
on:
  workflow_dispatch:
  schedule:
    # Run every monday at 3:00
    - cron:  '0 3 * * 1'

jobs:
  cron-e2e:
    runs-on: ubuntu-latest
    steps:

      - name: Branch master
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: run-e2e-branches
          client-payload: '{"branch": "master"}'

      - name: Branch 3.9
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: run-e2e-branches
          client-payload: '{"branch": "release_3_9"}'

      - name: Branch 3.8
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: run-e2e-branches
          client-payload: '{"branch": "release_3_8"}'
