name: "🚮 Close feedback PR"
on:
  schedule:
  - cron: "0 15 * * 1,3,5"

permissions:
  contents: read

jobs:
  stale:
    permissions:
      pull-requests: write  # for actions/stale to close stale PRs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v9.1.0
      with:
        days-before-pr-stale: 60
        days-before-pr-close: 14
        operations-per-run: 300
        close-pr-label: stale
        ignore-updates: false
        stale-pr-message: >
          The Lizmap project highly values your contribution and would love to see
          this work merged!
          Unfortunately this PR has not had any activity in the last 2 months and
          is being automatically marked as "stale".

          If there is no further activity on this pull request, it will be closed in two
          weeks.
